## Numpy

Numpy is a fundamental lobrary for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical function to operate on these data structures. In this lesson we will cover the basics of numpy focusing on arrays and vectorised operations.

In [2]:
!pip install numpy 

In [ ]:
## 1-D array 


import numpy as np

##create a array using numpy 
##create a 1D array


arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)       ##Output -> whenever there will be 1D array the output will be only single value in this case (5,)
                        ##No specific rows and columns 


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)                   ##This is two dimensional array 
                                    ##This basically means 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2-D array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
##Identity matrix 
np.eye(3)               ##All diagonal elements as 1 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##Attributes of numpy 

arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)
print("Data Type:",arr.dtype)   
print("Size:",arr.size)
print("Item Size:",arr.itemsize)



Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data Type: int64
Size: 6
Item Size: 8


In [17]:
##Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])


###Element wise addition 
print("Addition:",arr1+arr2)

###Element wise addition 
print("Subtraction:",arr1-arr2)

###Element wise Multiplication  
print("Multiplication:",arr1*arr2)

###Element wise Division 
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [18]:
##Universal function 

arr = np.array([2,3,4,5,6])

##square root
print(np.sqrt(arr))

##Exponential 
print(np.exp(arr))

##Sine
print(np.sin(arr))

##Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
##Array slicing and indexing 

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(arr[0][2])

3


In [ ]:
print(arr[1:])

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(arr[1:,2:])

array([[ 7,  8],
       [11, 12]])

In [29]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [38]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [39]:
##Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [40]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
##Statistical Concept

##Normalization 
##To have a means of 0 and standard deviation of 1 
data = np.array([1,2,3,4,5])

##Calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)


##Normalize the data 
normalized_data = (data-mean) / std_dev
print("Normalized data \n" , normalized_data)

Normalized data 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
##Calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)


##Normalize the data 
normalized_data = (data-mean) / std_dev
print("Normalized data \n" , normalized_data)

Normalized data 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean 
mean = np.mean(data)
print("Mean:",mean)

#Median
median = np.median(data)
print("Median:",median)

##Standard Deviation 
std_dev = np.std(data)
print("Standard Deviation:",std_dev)


##Variance 
variance = np.var(data)
print("Variance:",variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [54]:
##Logical Operation 

data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])